[package]
name = "fuzz-targets"
version = "0.1.0"
authors = ["Patrick Ventuzelo <ventuzelo.patrick@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2"
ssz = { package = "ethereum_ssz", version = "0.9.0" }
ssz_derive = { package = "ethereum_ssz_derive", version = "0.9.0" }
state_processing = { path = "../../../lighthouse/consensus/state_processing" }
types = { path = "../../../lighthouse/consensus/types" }
bls = { path = "../../../lighthouse/crypto/bls" }
lighthouse_network =  { path = "../../../lighthouse/beacon_node/lighthouse_network" }

## libp2p now comes via lighthouse_network; no direct pin here.
