#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
FUZZ_DIR="$ROOT/workspace/libfuzzer/fuzz"
CORPORA="$ROOT/workspace/corpora"
LOG_DIR="$ROOT/workspace/logs/rl_cov_compare"
mkdir -p "$LOG_DIR"

export CARGO_HOME="$ROOT/workspace/cargo-home"
export ETH2FUZZ_BEACONSTATE="$CORPORA/beaconstate"

DUR=${1:-600}
SEG=${2:-60}

get_targets() {
  (cd "$ROOT" && cargo run -- list | rg '^diff_')
}

corpora_label() {
  (cd "$ROOT" && cargo run -- corpora-label "$1" 2>/dev/null)
}

extract_cov_done() {
  # Prefer DONE cov lines for baseline (more stable)
  rg -n "DONE\s+cov:\s+[0-9]+" -N "$1" 2>/dev/null | awk '{for(i=1;i<=NF;i++){if($i=="cov:"){print $(i+1)}}}' | \
    awk 'NR==1{fc=$1} {lc=$1} END{ if(NR==0){print "0 0"} else {print fc, lc} }'
}

extract_cov_any() {
  # Fallback: any cov lines (works for RL pulse/REDUCE and baseline if no DONE)
  rg -n "cov:\s+[0-9]+" -N "$1" 2>/dev/null | awk '{for(i=1;i<=NF;i++){if($i=="cov:"){print $(i+1)}}}' | \
    awk 'NR==1{fc=$1} {lc=$1} END{ if(NR==0){print "0 0"} else {print fc, lc} }'
}

echo "target,mode,first_cov,last_cov,growth_per_min,logfile"

# detect cores and compute workers per target
TARGETS=( $(get_targets) )
NT=${#TARGETS[@]}
NCORES=$( (nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1) )
W=$(( NCORES / (NT>0?NT:1) )); if [ "$W" -lt 1 ]; then W=1; fi
export RAYON_NUM_THREADS=1

# run baseline in parallel
pids=()
for t in "${TARGETS[@]}"; do
  label=$(corpora_label "$t"); if [ -z "$label" ]; then label="attestation"; fi
  BLOG="$LOG_DIR/${t}_baseline.log"
  echo "[baseline] $t for ${DUR}s (CLI)"
  (cd "$ROOT" && cargo run -- target "$t" --fuzzer Libfuzzer --timeout $DUR) 2>&1 | tee "$BLOG" >/dev/null || true &
  pids+=( $! )
done
wait "${pids[@]}" || true

# run RL in parallel
pids=()
for t in "${TARGETS[@]}"; do
  RLOG="$LOG_DIR/${t}_rl.log"
  echo "[rl] $t total=${DUR}s segment=${SEG}s (threads=$W)"
  (cd "$ROOT" && cargo run -- rl-fuzz -q "$t" --fuzzer Libfuzzer --total $DUR --segment $SEG -n $W) \
    2>&1 | tee "$RLOG" >/dev/null || true &
  pids+=( $! )
done
wait "${pids[@]}" || true

# summarize coverage
for t in "${TARGETS[@]}"; do
  # Prefer baseline per-target fuzzer log if present (generated by libFuzzer runner tee)
  B_TAG=${ETH2FUZZ_TAG:-default}
  B_FUZZ_LOG="$ROOT/workspace/logs/$B_TAG/base/libfuzzer/logs/${t}.log"
  B_FUZZ_LOG_ALT="$ROOT/workspace/logs/$B_TAG/base/hfuzz/logs/${t}.log"
  BLOG="$LOG_DIR/${t}_baseline.log"
  B_SRC="$BLOG"; [ -f "$B_FUZZ_LOG" ] && B_SRC="$B_FUZZ_LOG"; [ -f "$B_FUZZ_LOG_ALT" ] && B_SRC="$B_FUZZ_LOG_ALT"
  read fc lc < <(extract_cov_done "$B_SRC") || true
  if [ "$fc" = "0" ] && [ "$lc" = "0" ]; then
    read fc lc < <(extract_cov_any "$B_SRC") || true
  fi
  gpm=0; if [ "$fc" != "" ] && [ "$lc" != "" ]; then gpm=$(python3 - <<PY
fc=$fc; lc=$lc; dur=$DUR
print((lc-fc)/max(dur/60.0,1.0))
PY
); fi
  echo "$t,baseline,$fc,$lc,$gpm,$B_SRC"

  RL_TAG=${ETH2FUZZ_TAG:-default}
  RL_FUZZ_LOG="$ROOT/workspace/logs/$RL_TAG/rl/libfuzzer/logs/${t}.log"
  RL_FUZZ_LOG_ALT="$ROOT/workspace/logs/$RL_TAG/rl/hfuzz/logs/${t}.log"
  RLOG="$LOG_DIR/${t}_rl.log"
  SRC_LOG="$RLOG"; [ -f "$RL_FUZZ_LOG" ] && SRC_LOG="$RL_FUZZ_LOG"; [ -f "$RL_FUZZ_LOG_ALT" ] && SRC_LOG="$RL_FUZZ_LOG_ALT"
  read fc2 lc2 < <(extract_cov_any "$SRC_LOG") || true
  gpm2=0; if [ "$fc2" != "" ] && [ "$lc2" != "" ]; then gpm2=$(python3 - <<PY
fc=$fc2; lc=$lc2; dur=$DUR
print((lc-fc)/max(dur/60.0,1.0))
PY
); fi
  echo "$t,rl,$fc2,$lc2,$gpm2,$SRC_LOG"
done

echo "Done. Logs under $LOG_DIR"
